### ISSUE TITLE
AttributeError: Can't pickle local object 'CreateDataLoader.<locals>.my_collate'

### ISSUE THREAD

**Issue by LJYlearner** [zhangjunh/DR-GAN-by-pytorch#13]
i want to know what's the problem when i run train.py

**Comment by east-wang** [comment]
所以你解决了吗

**Comment by zhangjunh** [comment]
@east-wang 你试试pytorch 0.2.0。这个是我很久之前写的代码，pytorch版本比较老。

**Comment by east-wang** [comment]
好的，非常感谢您的回复！



在 2019-07-18 20:23:22，"Junhao Zhang" <notifications@github.com> 写道：


@east-wang 你试试pytorch 0.2.0。这个是我很久之前写的代码，pytorch版本比较老。
