### ISSUE TITLE
If  only batch_size=3 is ok ? I change batch_size=others , both errors.

### ISSUE THREAD

**Issue by lingling0319** [zhangjunh/DR-GAN-by-pytorch#14]

**Comment by zhangjunh** [comment]
Batch_size = 3 means your network loads 3 * 14 = 42 images in one batch( cfp-dataset has 10 Frontal and 4 Profile images of each 500 individuals). So if your GPU is out of memory, try to change it to a lower value.

**Comment by hxl835097324** [comment]
If I use the Multi-PIE dataset,  each processed subset has 520 images. How do I change the batch_size?
