### ISSUE TITLE
Pre-trained model available?

### ISSUE THREAD

**Issue by balag59** [zhangjunh/DR-GAN-by-pytorch#16]
Hi,
Thank you so much for this work! It would be incredibly helpful if you could release a pre-trained model that can be used for testing and reproducing the results. I'm currently in the process of training this and it takes a very long time to train 10000 epochs. I've reached around 4500 epochs and my results are still pretty bad and near unusable. I've not modified any hyperparameters and am using all the default ones.
Thanks!

**Comment by zhangjunh** [comment]
Hi @balag59 , the model was lost before this code was uploaded, and it took a long time for training with a 1080TI.
