### ISSUE TITLE
 one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by pandeshraddha** [zhangjunh/DR-GAN-by-pytorch#17]
I am trying to run the DR GAN code and specifically facing the error in DRGAN.py . 
![image](https://user-images.githubusercontent.com/12835584/125508804-cc96af3f-ab82-4420-a092-31fac0154a40.png)

**Comment by zhangjunh** [comment]
Which version of pytorch? The code was based on 0.2.

**Comment by pandeshraddha** [comment]
Hello Zhang,

I am trying to use 1.0.2. I will try to depreciate my pytorch environment
and try again.

Thanks for your response.

Sincerely,

Shraddha
