### ISSUE TITLE
hello i want to train this model. but when i run train.py on cpu i gives some errors shown below  File "/Users/apple/Downloads/DR-GAN-by-pytorch-master/train.py", line 25, in <module>     err = err(model.save_dir)   File "util/utils.py", line 15, in __init__     os.mknod(self.path) PermissionError: [Errno 1] Operation not permitted . can you help me to solve it?

### ISSUE THREAD

**Issue by NomiMalik0207** [zhangjunh/DR-GAN-by-pytorch#7]

**Comment by zhangjunh** [comment]
Hi @NomiMalik0207 , did you run this code in a Linux system? It seems that you don't have enough permission to create the .txt file to save logs. You should try some methods to escalate privilege, or create file 'error_record.txt' in the folder './checkpoints/Y-m-d_H-M-S' manually.
